export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const MY_PROFILE_RETRIEVED = 'MY_PROFILE_RETRIEVED';
export const MY_PROFILE_RETRIEVAL_FAILED = 'MY_PROFILE_RETRIEVAL_FAILED';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_SAVED = 'PROFILE_SAVED';
export const PROFILE_SAVED_FAIL = 'PROFILE_SAVED_FAIL';
export const PROFILE_DELETED = 'PROFILE_DELETED';
export const PROFILE_DELETED_FAIL = 'PROFILE_DELETED_FAIL';
export const CLEAR_PROFILE_ALERTS = 'CLEAR_PROFILE_ALERTS';
export const LOADING_MY_PROFILE = 'LOADING_MY_PROFILE';
export const DONE_LOADING_PROFILE = 'DONE_LOADING_PROFILE';
export const HAS_PROFILE = 'HAS_PROFILE';

export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const GET_ALL_PROFILES_FAIL = 'GET_ALL_PROFILES_FAIL';

export const LOADING_USER_PROFILE = 'LOADING_USER_PROFILE';
export const DONE_LOADING_USER_PROFILE = 'DONE_LOADING_USER_PROFILE';
export const FAILED_LOADING_USER_PROFILE = 'FAILED_LOADING_USER_PROFILE';

export const USERNAME_RETRIEVED = 'USERNAME_RETRIEVED';
export const USERNAME_RETRIVAL_FAILED = 'USERNAME_RETRIVAL_FAILED';

export const CONTACT_ADDED = 'CONTACT_ADDED';
export const ADD_CONTACT_LOADING = 'ADD_CONTACT_LOADING';
export const CLEAR_ADD_CONTACT_ALERT = 'CLEAR_ADD_CONTACT_ALERT';
export const CONTACT_ADDED_FAILED = 'CONTACT_ADDED_FAILED';

export const CONTACT_REMOVED = 'CONTACT_REMOVED';
export const CONTACT_REMOVED_FAILED = 'CONTACT_REMOVED_FAILED';

export const GETTING_MESSAGES = 'GETTING_MESSAGES';
export const MESSAGES_RETRIEVED = 'MESSAGES_RETRIEVED';
export const MESSAGES_RETRIEVAL_FAILED = 'MESSAGES_RETRIEVAL_FAILED';

export const MESSAGE_SENT_SUCCESSFULLY = 'MESSAGE_SENT_SUCCESSFULLY';
export const MESSAGE_SENT_FAILED = 'MESSAGE_SENT_FAILED';

export const SET_SELECTED_THREAD = 'SET_SELECTED_THREAD';
export const CLEAR_SELECTED_THREAD = 'CLEAR_SELECTED_THREAD';

export const ADD_PROFILE_TO_NEW_THREAD = 'ADD_PROFILE_TO_NEW_THREAD';

export const SET_DROPDOWN = 'SET_DROPDOWN';
export const CLEAR_NEW_THREAD = 'CLEAR_NEW_THREAD';

export const GETTING_SEARCH_RESULTS = 'GETTING_SEARCH_RESULTS';
export const FAILED_GETTING_SEARCH_RESULTS = 'FAILED_GETTING_SEARCH_RESULTS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const SETTING_SEARCH_VALUE = 'SETTING_SEARCH_VALUE';

export const PROFILE_ERROR = 'PROFILE_ERROR';

export const LOADING_SEARCH_RESULTS = 'LOADING_SEARCH_RESULTS';
export const DONE_LOADING_SEARCH_RESULTS = 'DONE_LOADING_SEARCH_RESULTS';

export const SENDING_MESSAGE_LOADING = 'SENDING_MESSAGE_LOADING';

export const SAVE_PROFILE_LOADING = 'SAVE_PROFILE_LOADING';

export const SET_ON_EDIT_PROFILE_PAGE = 'SET_ON_EDIT_PROFILE_PAGE';

export const USERNAME_TAKEN_ERROR = 'USERNAME_TAKEN_ERROR';
export const TEST_PROFILE_ERROR = 'TEST_PROFILE_ERROR';
